namespace DataBaseProject
{
    partial class marfa
    {
        /// <summary>
        /// Required constructor variable.
        /// </summary> 
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Free up all used resources.
        /// </summary>
        /// <param name = "disposing"> true if the managed resource is to be disposed of; false otherwise. </param> 
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by Windows Form Designer

        /// <summary>
        /// Required method for constructor support - do not modify
        /// the contents of this method using a code editor.
        /// </summary> 
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(marfa));
            this.panel1 = new System.Windows.Forms.Panel();
            this.button_Export = new System.Windows.Forms.Button();
            this.button_Import = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.emailtxt = new System.Windows.Forms.TextBox();
            this.nametxt = new System.Windows.Forms.TextBox();
            this.surntxt = new System.Windows.Forms.TextBox();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.button_Delete = new System.Windows.Forms.Button();
            this.button_Update = new System.Windows.Forms.Button();
            this.button_Add = new System.Windows.Forms.Button();
            this.button_clear = new System.Windows.Forms.Button();
            this.label4 = new System.Windows.Forms.Label();
            this.count_name = new System.Windows.Forms.TextBox();
            this.orig_price = new System.Windows.Forms.TextBox();
            this.sale = new System.Windows.Forms.TextBox();
            this.summa = new System.Windows.Forms.TextBox();
            this.button1 = new System.Windows.Forms.Button();
            this.sale_value = new System.Windows.Forms.TextBox();
            this.data_check = new System.Windows.Forms.Button();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.panel1.Controls.Add(this.data_check);
            this.panel1.Controls.Add(this.button1);
            this.panel1.Controls.Add(this.summa);
            this.panel1.Controls.Add(this.sale);
            this.panel1.Controls.Add(this.orig_price);
            this.panel1.Controls.Add(this.sale_value);
            this.panel1.Controls.Add(this.count_name);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.button_Export);
            this.panel1.Controls.Add(this.button_Import);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.emailtxt);
            this.panel1.Controls.Add(this.nametxt);
            this.panel1.Controls.Add(this.surntxt);
            this.panel1.Controls.Add(this.dataGridView1);
            this.panel1.Controls.Add(this.button_Delete);
            this.panel1.Controls.Add(this.button_Update);
            this.panel1.Controls.Add(this.button_Add);
            this.panel1.Controls.Add(this.button_clear);
            resources.ApplyResources(this.panel1, "panel1");
            this.panel1.Name = "panel1";
            // 
            // button_Export
            // 
            this.button_Export.BackColor = System.Drawing.Color.Tomato;
            this.button_Export.Cursor = System.Windows.Forms.Cursors.Hand;
            this.button_Export.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            resources.ApplyResources(this.button_Export, "button_Export");
            this.button_Export.ForeColor = System.Drawing.Color.Black;
            this.button_Export.Name = "button_Export";
            this.button_Export.UseVisualStyleBackColor = false;
            this.button_Export.Click += new System.EventHandler(this.OnExportClick);
            // 
            // button_Import
            // 
            this.button_Import.BackColor = System.Drawing.Color.Tomato;
            this.button_Import.Cursor = System.Windows.Forms.Cursors.Hand;
            this.button_Import.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            resources.ApplyResources(this.button_Import, "button_Import");
            this.button_Import.ForeColor = System.Drawing.Color.Black;
            this.button_Import.Name = "button_Import";
            this.button_Import.UseVisualStyleBackColor = false;
            this.button_Import.Click += new System.EventHandler(this.OnButtonImport);
            // 
            // label3
            // 
            resources.ApplyResources(this.label3, "label3");
            this.label3.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label3.Name = "label3";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label2.Name = "label2";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label1.Name = "label1";
            // 
            // emailtxt
            // 
            resources.ApplyResources(this.emailtxt, "emailtxt");
            this.emailtxt.Name = "emailtxt";
            // 
            // nametxt
            // 
            resources.ApplyResources(this.nametxt, "nametxt");
            this.nametxt.Name = "nametxt";
            // 
            // surntxt
            // 
            resources.ApplyResources(this.surntxt, "surntxt");
            this.surntxt.Name = "surntxt";
            // 
            // dataGridView1
            // 
            this.dataGridView1.BackgroundColor = System.Drawing.Color.White;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            resources.ApplyResources(this.dataGridView1, "dataGridView1");
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.MouseClick += new System.Windows.Forms.MouseEventHandler(this.dataGridView1_MouseClick);
            // 
            // button_Delete
            // 
            this.button_Delete.BackColor = System.Drawing.Color.Red;
            this.button_Delete.Cursor = System.Windows.Forms.Cursors.Hand;
            resources.ApplyResources(this.button_Delete, "button_Delete");
            this.button_Delete.Name = "button_Delete";
            this.button_Delete.UseVisualStyleBackColor = false;
            this.button_Delete.Click += new System.EventHandler(this.OnButtonDelete);
            // 
            // button_Update
            // 
            this.button_Update.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.button_Update.Cursor = System.Windows.Forms.Cursors.Hand;
            resources.ApplyResources(this.button_Update, "button_Update");
            this.button_Update.Name = "button_Update";
            this.button_Update.UseVisualStyleBackColor = false;
            this.button_Update.Click += new System.EventHandler(this.OnButtonUpdate);
            // 
            // button_Add
            // 
            this.button_Add.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.button_Add.Cursor = System.Windows.Forms.Cursors.Hand;
            this.button_Add.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            resources.ApplyResources(this.button_Add, "button_Add");
            this.button_Add.ForeColor = System.Drawing.Color.Black;
            this.button_Add.Name = "button_Add";
            this.button_Add.UseVisualStyleBackColor = false;
            this.button_Add.Click += new System.EventHandler(this.OnButtonAdd);
            // 
            // button_clear
            // 
            this.button_clear.BackColor = System.Drawing.Color.Red;
            this.button_clear.Cursor = System.Windows.Forms.Cursors.Hand;
            this.button_clear.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.button_clear.FlatAppearance.BorderSize = 2;
            resources.ApplyResources(this.button_clear, "button_clear");
            this.button_clear.Name = "button_clear";
            this.button_clear.UseVisualStyleBackColor = false;
            this.button_clear.Click += new System.EventHandler(this.OnButtonClear);
            // 
            // label4
            // 
            resources.ApplyResources(this.label4, "label4");
            this.label4.Name = "label4";
            // 
            // count_name
            // 
            this.count_name.BackColor = System.Drawing.SystemColors.Info;
            resources.ApplyResources(this.count_name, "count_name");
            this.count_name.Name = "count_name";
            // 
            // orig_price
            // 
            this.orig_price.BackColor = System.Drawing.SystemColors.Info;
            resources.ApplyResources(this.orig_price, "orig_price");
            this.orig_price.Name = "orig_price";
            // 
            // sale
            // 
            this.sale.BackColor = System.Drawing.SystemColors.Info;
            resources.ApplyResources(this.sale, "sale");
            this.sale.Name = "sale";
            // 
            // summa
            // 
            this.summa.BackColor = System.Drawing.SystemColors.Info;
            resources.ApplyResources(this.summa, "summa");
            this.summa.Name = "summa";
            // 
            // button1
            // 
            resources.ApplyResources(this.button1, "button1");
            this.button1.Name = "button1";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // sale_value
            // 
            this.sale_value.BackColor = System.Drawing.SystemColors.Info;
            resources.ApplyResources(this.sale_value, "sale_value");
            this.sale_value.Name = "sale_value";
            // 
            // data_check
            // 
            resources.ApplyResources(this.data_check, "data_check");
            this.data_check.Name = "data_check";
            this.data_check.UseVisualStyleBackColor = true;
            this.data_check.Click += new System.EventHandler(this.data_check_Click);
            // 
            // marfa
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Highlight;
            this.Controls.Add(this.panel1);
            this.MaximizeBox = false;
            this.Name = "marfa";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Button button_Delete;
        private System.Windows.Forms.Button button_Update;
        private System.Windows.Forms.Button button_Add;
        private System.Windows.Forms.Button button_clear;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox emailtxt;
        private System.Windows.Forms.TextBox nametxt;
        private System.Windows.Forms.TextBox surntxt;
        private System.Windows.Forms.DataGridView dataGridView1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button button_Export;
        private System.Windows.Forms.Button button_Import;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.TextBox summa;
        private System.Windows.Forms.TextBox sale;
        private System.Windows.Forms.TextBox orig_price;
        private System.Windows.Forms.TextBox count_name;
        private System.Windows.Forms.TextBox sale_value;
        private System.Windows.Forms.Button data_check;
    }
}

